### ISSUE TITLE
meanf.txt

### ISSUE THREAD

**Issue by wwencc** [luckybird1994/SAMCOD#2]
Hello,thank you for your work！I'm confused about the meanf.txt，how can i get it？Thanks！

**Comment by luckybird1994** [comment]
> Hello,thank you for your work！I'm confused about the meanf.txt，how can i get it？Thanks！

For each image, SAM would predict multiple binary masks. We calculate the mean f-measure of each mask and write them to the meanf.txt.

**Comment by RainloongCao** [comment]
Hello,thank you for your work！ 
I can't find the place to generate meanf.txt in your code, can you please tell me the code to generate this file, thank you!
